import { ANIMATIONS } from '../components/NUIDefaultBottomSheet/types';

const DEFAULT_HEIGHT = '50%';
const DEFAULT_ANIMATION = ANIMATIONS.SLIDE;
const DEFAULT_OPEN_ANIMATION_DURATION = 300;
const DEFAULT_CLOSE_ANIMATION_DURATION = 300;
const DEFAULT_HANDLE_BAR_DEFAULT_HEIGHT = 25;

const HIT_STOP = { top: 20, bottom: 20 };
const CLOSE_THRESHOLD = 3;
const BOTTOM_THRESHOLD = 10;
const MIN_VELOCITY_Y = 1000;

export {
  DEFAULT_HEIGHT,
  DEFAULT_ANIMATION,
  DEFAULT_OPEN_ANIMATION_DURATION,
  DEFAULT_CLOSE_ANIMATION_DURATION,
  DEFAULT_HANDLE_BAR_DEFAULT_HEIGHT,
  HIT_STOP,
  CLOSE_THRESHOLD,
  MIN_VELOCITY_Y,
  BOTTOM_THRESHOLD,
};
